Make container ID as optional prop
mercadopago/sdk-react pull request #110
Opened 2024-10-21 07:42 UTC by luisguerra

This PR enables the ability to modify the div to avoid collision with existing ID's or define multiple elements

2024-10-23 02:26 UTC, luisguerra commented
cc @francineemilia @icaldana @AdaltonLeite @AleFossati @lemazzo

2024-10-23 12:15 UTC, AleFossati commented
Olá @luisguerra, assim que possível faremos a revisão e teste das alterações.
Obrigado pela contribuição!

2024-10-23 12:36 UTC, AdaltonLeite commented on src/bricks/brand/index.tsx
> +  divId = 'brandBrick_container',
```suggestion
  id = 'brandBrick_container',
```

2024-10-23 12:36 UTC, AdaltonLeite commented on src/bricks/brand/index.tsx
> +  return <div id={divId}></div>;
```suggestion
  return <div id={id}></div>;
```

2024-10-23 12:37 UTC, AdaltonLeite commented on src/bricks/brand/brand.test.tsx
> +        divId="customBrandBrick_container"
```suggestion
        id="customBrandBrick_container"
```

2024-10-23 12:40 UTC, AdaltonLeite commented on src/bricks/brand/index.tsx
> +      divId,
```suggestion
      divId: id,
```

2024-10-23 12:41 UTC, AdaltonLeite commented on src/bricks/brand/types.ts
> +  divId?: string;
```suggestion
  id?: string;
```

2024-11-04 02:53 UTC, luisguerra commented
(Sorry I don't speak Portuguese 😅 , hello From Mexico, so I will write in English)
Thanks for feedback @AdaltonLeite, makes sense. I have made the requested changes

2024-11-04 19:11 UTC, AleFossati requested changes
Hello @luisguerra,

I have tested the changes and it looks great, there's only a few changes needed, it seems that the default values in the comments are all referencing wallet brick.

After this fix, I think that we are ready to merge!

2024-11-04 19:11 UTC, AleFossati commented on src/bricks/cardPayment/type.ts
> +   * Optional. Container ID where the Brick will be rendered. Default: 'walletBrick_container'
```suggestion
   * Optional. Container ID where the Brick will be rendered. Default: 'cardPaymentBrick_container'
```

2024-11-04 19:11 UTC, AleFossati commented on src/bricks/payment/type.ts
> +   * Optional. Container ID where the Brick will be rendered. Default: 'walletBrick_container'
```suggestion
   * Optional. Container ID where the Brick will be rendered. Default: 'paymentBrick_container'
```

2024-11-04 19:11 UTC, AleFossati commented on src/bricks/statusScreen/types.ts
> +   * Optional. Container ID where the Brick will be rendered. Default: 'walletBrick_container'
```suggestion
   * Optional. Container ID where the Brick will be rendered. Default: 'statusScreenBrick_container'
```

2024-11-13 11:52 UTC, icaldana commented
@luisguerra hey, could you please check @AleFossati comments? Thank you a lot!

2024-12-12 14:53 UTC, icaldana approved these changes

2024-12-12 14:55 UTC, AleFossati approved these changes

2024-12-12 14:58 UTC, merged