Add Review and Confirm to MLA and new prop additionalInformation of shipping
mercadopago/sdk-react pull request #92
Opened 2024-02-07 13:07 UTC by lemazzo

2024-02-07 14:47 UTC, meliguicarvalho submitted a review, later dismissed

2024-02-07 16:02 UTC, icaldana submitted a review, later dismissed

2024-02-07 16:24 UTC, francineemilia submitted a review, later dismissed

2024-02-07 19:13 UTC, AleFossati requested changes

2024-02-07 19:13 UTC, AleFossati commented on src/bricks/payment/type.ts
> +  additionalInformation: string;
Este campo precisa ser opcional.

```suggestion
  additionalInformation?: string;
```

2024-02-08 11:02 UTC, AleFossati approved these changes

2024-02-08 13:19 UTC, merged